SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FRAME_PER_SECOND = 60

PLAYER_HEIGHT = 50
PLAYER_WIDTH = 100

PLAYER_MOVE_VELOCITY = 0  # speed init
PLAYER_MOVE_VELOCITY_LIMIT = 220 # speed max
PLAYER_MOVE_ACC = 600 # 加速度
PLAYER_FRICTION = 0.98 # 摩擦力
PLAYER_FORWARD_ANGLE = 90 # 游戏坐标中,顺时针转动角度
PLAYER_ROTATE_VELOCITY_LIMIT = 140 # 转动的速度限制
PLAYER_ROTATE_VELOCITY = 0 # 初始转动的速度

PLAYER_ROTATE_START_VELOCITY = 10 # 当速度达到一定后,才能转弯
